# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-24 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180524_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='provided_flexibility_time',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='target_charging_level',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=30),
        ),
    ]
