# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171113_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvite',
            name='consumed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
