# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-24 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180523_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BlockConfig'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SessionConfig'),
        ),
    ]
