# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171208_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinvite',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
