# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-10 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171208_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvite',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
