# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-10 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171210_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
