# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-16 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20171210_1946'),
        ('core', '0007_customuser_profile_image'),
    ]

    operations = [
    ]
