# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-06 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20171216_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(blank=True, default='default.png', max_length=128),
        ),
    ]
