# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-15 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180306_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvite',
            name='has_account',
            field=models.BooleanField(default=False),
        ),
    ]
