# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-18 16:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_groupinvite_has_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinvite',
            name='has_account',
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='invitee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
