# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-03-23 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bookrecommendationforfriend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookrecommendationforfriend',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='bookrecommendationforfriend',
            name='book',
        ),
        migrations.AddField(
            model_name='bookrecommendationforfriend',
            name='book_author',
            field=models.CharField(default='', max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookrecommendationforfriend',
            name='book_title',
            field=models.CharField(default='', max_length=63),
            preserve_default=False,
        ),
    ]
