# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-22 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_bookrecommendationforfriend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('block_status', models.CharField(blank=True, max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='BlockConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clocktime', models.DateTimeField(default=django.utils.timezone.now)),
                ('charge_status', models.DecimalField(blank=True, decimal_places=5, max_digits=30)),
                ('charge_distance', models.DecimalField(blank=True, decimal_places=5, max_digits=30)),
                ('time_to_full_charge', models.DecimalField(blank=True, decimal_places=5, max_digits=30)),
                ('flexibility_time_request', models.DecimalField(blank=True, decimal_places=5, max_digits=30)),
                ('flexibility_charge_level_request', models.DecimalField(blank=True, decimal_places=5, max_digits=30)),
                ('flexibility_time_provision', models.DecimalField(blank=True, decimal_places=5, max_digits=30)),
                ('flexibility_charge_level_provision', models.DecimalField(blank=True, decimal_places=5, max_digits=30)),
                ('full_charge_price', models.DecimalField(blank=True, decimal_places=5, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('nudge', models.CharField(max_length=255)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_of_participants', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nudge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('heading', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_status', models.CharField(blank=True, max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='SessionBlockConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BlockConfig')),
            ],
        ),
        migrations.CreateModel(
            name='SessionConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=31)),
                ('number_of_sessions', models.PositiveSmallIntegerField(blank=True)),
                ('session_config_status', models.CharField(default='active', max_length=31)),
            ],
        ),
        migrations.RenameField(
            model_name='bookrecommendationforfriend',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='bookrecommendationforfriend',
            name='book',
        ),
        migrations.AddField(
            model_name='bookrecommendationforfriend',
            name='book_author',
            field=models.CharField(default='xxx', max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookrecommendationforfriend',
            name='book_title',
            field=models.CharField(default='xxx', max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionblockconfig',
            name='session_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SessionConfig'),
        ),
        migrations.AddField(
            model_name='session',
            name='session_config',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.SessionConfig'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventhistory',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Session'),
        ),
        migrations.AddField(
            model_name='blockconfig',
            name='nudge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Nudge'),
        ),
        migrations.AddField(
            model_name='block',
            name='block_config',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.BlockConfig'),
        ),
        migrations.AddField(
            model_name='block',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Session'),
        ),
        migrations.AddField(
            model_name='block',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sessionblockconfig',
            unique_together=set([('session_config', 'block_config')]),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('user', 'session_config')]),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set([('session', 'block_config')]),
        ),
    ]
