# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-10 22:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180323_0137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BlockConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clocktime', models.DateTimeField(default=django.utils.timezone.now)),
                ('charge_status', models.DecimalField(decimal_places=5, max_digits=50)),
                ('charge_price', models.DecimalField(decimal_places=5, max_digits=50)),
                ('flexibility_hours', models.DecimalField(decimal_places=5, max_digits=50)),
                ('flexiblity_clock', models.DateTimeField(default=django.utils.timezone.now)),
                ('nudge', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('nudge', models.CharField(max_length=255)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('number_of_participants', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='SessionConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_first', models.CharField(blank=True, max_length=31)),
                ('block_second', models.CharField(blank=True, max_length=31)),
                ('block_third', models.CharField(blank=True, max_length=31)),
                ('block_fourth', models.CharField(blank=True, max_length=31)),
                ('block_fifth', models.CharField(blank=True, max_length=31)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='session_config',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.SessionConfig'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventhistory',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Session'),
        ),
        migrations.AddField(
            model_name='block',
            name='block_config',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.BlockConfig'),
        ),
        migrations.AddField(
            model_name='block',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('user', 'experiment', 'session_config')]),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set([('user', 'block_config')]),
        ),
    ]
