# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-10 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180510_2106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set([('user', 'session')]),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([('user', 'experiment')]),
        ),
    ]
