# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-16 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180510_2246'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='block',
            unique_together=set([]),
        ),
    ]
