# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-19 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180516_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionconfig',
            name='block_fifth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_fifth', to='core.BlockConfig'),
        ),
        migrations.AlterField(
            model_name='sessionconfig',
            name='block_first',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_first', to='core.BlockConfig'),
        ),
        migrations.AlterField(
            model_name='sessionconfig',
            name='block_fourth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_fourth', to='core.BlockConfig'),
        ),
        migrations.AlterField(
            model_name='sessionconfig',
            name='block_second',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_second', to='core.BlockConfig'),
        ),
        migrations.AlterField(
            model_name='sessionconfig',
            name='block_third',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_third', to='core.BlockConfig'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='session',
            name='experiment',
        ),
    ]
