# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-19 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180519_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionBlockConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BlockConfig')),
            ],
        ),
        migrations.RemoveField(
            model_name='sessionconfig',
            name='block_fifth',
        ),
        migrations.RemoveField(
            model_name='sessionconfig',
            name='block_first',
        ),
        migrations.RemoveField(
            model_name='sessionconfig',
            name='block_fourth',
        ),
        migrations.RemoveField(
            model_name='sessionconfig',
            name='block_second',
        ),
        migrations.RemoveField(
            model_name='sessionconfig',
            name='block_third',
        ),
        migrations.AddField(
            model_name='sessionconfig',
            name='name',
            field=models.CharField(blank=True, max_length=31),
        ),
        migrations.AddField(
            model_name='sessionblockconfig',
            name='session_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SessionConfig'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionblockconfig',
            unique_together=set([('session_config', 'block_config')]),
        ),
    ]
